### ISSUE TITLE
mocking imports/require in jest

### ISSUE THREAD

**Issue by omenking** [omenking/swap-n-pop#146]
Before I could mock using `mock-require` though need to find a new solution to mock objects for testing. Figuring this out will resolving the majority of failing tests.

```
import store_mock    from 'helpers/store_mock'
import electron_mock from 'helpers/electron_mock'
mock('common/store', store_mock)
mock('electron'    , electron_mock)
```

You can run test suite via `npm test`

**Comment by omenking** [comment]
I thought maybe this but no luck
```ts
import store_mock    from 'helpers/store_mock'
import electron_mock from 'helpers/electron_mock'
jest.mock('common/store', ()=> store_mock)
jest.mock('electron'    , ()=> electron_mock)
```

**Comment by omenking** [comment]
```ts
const chai     = require('chai')
const sinon    = require('sinon')
const mock     = require('mock-require')

global.sinon    = sinon
global.mock     = mock

const electron = require('helpers/electron_mock')
const store    = require('helpers/store_mock')

chai.should()

global.electron = electron
global.store    = store

```

So setting the global doesn't appear to be overriding the `import` of `common/store` used in  `controls.js`

```
TypeError: Cannot read property 'app' of undefined

      at new Store (src/common/store.ts:12:57)
      at Object.<anonymous> (src/renderer/core/controls.ts:6:13)
      at Object.<anonymous> (src/renderer/core/game.ts:4:18)
      at Object.<anonymous> (src/renderer/states/mode_vs.ts:15:14)
      at Object.<anonymous> (spec/unit/renderer/components/playfield.spec.ts:4:17)
```

**Comment by omenking** [comment]
Trying out `jest.setMock`

https://facebook.github.io/jest/docs/en/jest-object.html#jestsetmockmodulename-moduleexports

**Comment by omenking** [comment]
Its possible ts-jest could be at fault since it doesn't use commonjs and has an extra step where it transpiles with babel.
https://github.com/kulshekhar/ts-jest/issues/258

**Comment by omenking** [comment]
All of theses didn't work.
```
jest.mock
jest.setMock
mock-require
```
So I just specified what we wanted mocked in the moduleNameMapper.
Now the only drawback here is you don't have fine tune control to unmock these objects.
For instance it's going to be hard to write test for `common/store`

However this just works. So I'm fine with the limitations
```
  moduleNameMapper: {
    "^core/game$"       : "<rootDir>/spec/mocks/game.mock.ts",
    "^electron$"        : "<rootDir>/spec/mocks/electron.mock.ts",
    "^common/store$"    : "<rootDir>/spec/mocks/store.mock.ts",
    "^main/(.*)$"       : "<rootDir>/src/main/$1",
    "^common/(.*)$"     : "<rootDir>/src/common/$1",
    "^components/(.*)$" : "<rootDir>/src/renderer/components/$1",
    "^core/(.*)$"       : "<rootDir>/src/renderer/core/$1",
    "^states/(.*)$"     : "<rootDir>/src/renderer/states/$1",
    "^ui/(.*)$"         : "<rootDir>/src/renderer/ui/$1"
  },
```

**Comment by omenking** [comment]
To really fix this problem I think I would have to make a bare bones example and see what gets outputted. 

My research indicates it could be around hoisting mocks, as babel and jest will both host, or could just be that these paths aren't picked up from tsconfig.
